<?php namespace ProcessWire;

class PageListSelectMultipleQuickly extends WireData implements Module {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Page List Select Multiple Quickly',
			'summary' => 'Modifies PageListSelectMultiple to allow you to select multiple pages without the tree closing.',
			'version' => '0.1.1',
			'author' => 'Robin Sallis',
			'href' => 'https://github.com/Toutouwai/PageListSelectMultipleQuickly',
			'icon' => 'fast-forward',
			'autoload' => 'template=admin',
			'requires' => 'ProcessWire>=3.0.0, PHP>=5.4.0',
		);
	}

	/**
	 * Ready
	 */
	public function ready() {
		$this->addHookAfter('InputfieldPageListSelectMultiple::renderReadyHook', $this, 'afterRenderReady');
		$this->addHookAfter('InputfieldPage::renderReadyHook', $this, 'afterInputfieldPageRenderReady');
	}

	/**
	 * After InputfieldPageListSelectMultiple::renderReady
	 * Add JS and CSS dependencies
	 *
	 * @param HookEvent $event
	 */
	protected function afterRenderReady(HookEvent $event) {
		$config = $this->wire('config');
		$info = $this->getModuleInfo();
		$version = $info['version'];
		$config->styles->add($config->urls->$this . "{$this}.css?v=$version");
		$config->scripts->add($config->urls->$this . "{$this}.js?v=$version");
		$js_config = [
			'close_button_label' => $this->_('Close'),
			'select_button_label' => $this->_('Select'),
		];
		$config->js($this->className, $js_config);
	}

	/**
	 * After InputfieldPage::renderReady
	 * Add identifying wrap class
	 *
	 * @param HookEvent $event
	 */
	protected function afterInputfieldPageRenderReady(HookEvent $event) {
		/* @var InputfieldPage $inputfield */
		$inputfield = $event->object;
		if($inputfield->inputfield != 'InputfieldPageListSelectMultiple') return;
		$inputfield->addClass('select-quickly', 'wrapClass');
	}

}
